### ISSUE TITLE
Friend bar showing default theme instead of Purpura

### ISSUE THREAD

**Issue by Darrel-Santoso** [blueb442/purpura#5]
**Describe the bug**
Friend tab is showing the default theme instead of the Purpura theme

**Where is it?**
Friend's tab

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/79248128/148879631-11f59cb0-535f-4a08-baeb-0692b02ea87f.png)

**Version**
 Version 2.8.1
**Other Information**
Nitro tab is also misaligned.

**Comment by blueb442** [comment]
There's been a lot of issues recently due to discord pushing an update which changed the class named that modify a large amount of discord, causing the theme to break in these places. Working on fixing it now, but its going to be a while before I get everything.

**Comment by blueb442** [comment]
Fixed!
