### ISSUE TITLE
Emote preview showing default theme instead of purpura

### ISSUE THREAD

**Issue by Darrel-Santoso** [blueb442/purpura#6]
**Describe the bug**
Emote preview showing default theme instead of the purpura theme

**Where is it?**
The emote preview section

**Screenshots**
![Screenshot 2022-01-11 112616](https://user-images.githubusercontent.com/79248128/148881033-639026d3-9dbe-4c74-9357-1afdb5cb7cc7.png)

**Version**
 - Version 2.8.1

**Comment by blueb442** [comment]
There's been a lot of issues recently due to discord pushing an update which changed the class named that modify a large amount of discord, causing the theme to break in these places. It's next on my list, but its going to be a while before I get everything.

**Comment by blueb442** [comment]
Fixed!
